
on:
  push:
    branches:
      - master

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v2
      - uses: https://code.forgejo.org/actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install -g pnpm yarn
          yarn
      - name: Build
        run: |
          mkdir -p .vercel
          yarn vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          yarn vercel build --token ${{ secrets.VERCEL_TOKEN }}
          yarn vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --prebuilt