
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v2
      - uses: https://code.forgejo.org/actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
      - name: Build
        run: |
          pnpm build
          pnpm vercel --token ${{ secrets.VERCEL_TOKEN }} --prod